name: Test, Build & Push (Node.js + Angular)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Step 1: Checkout repository
      # -----------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------
      # Step 2: Setup Node.js
      # -----------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # -----------------------------
      # Step 3: Backend - Install deps & run Jest tests
      # -----------------------------
      - name: Backend - Install dependencies & run Jest tests
        working-directory: ./code/petmanagement_backend_rajalakshmi
        run: |
          npm ci
          # Install jest (and ts-jest if TypeScript backend)
          npm install --save-dev jest @types/jest ts-jest
          # Initialize Jest config if not present
          npx ts-jest config:init || true
          # Run backend tests
          npm test

      # -----------------------------
      # Step 4: Frontend - Install deps & run Angular tests
      # -----------------------------
      - name: Frontend - Install dependencies
        working-directory: ./code/petmanagement_frontend_rajalakshmi
        run: |
          npm ci
          npm install -g @angular/cli

      # -----------------------------
      # Step 5: Login to Docker Hub
      # -----------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # Step 6: Build & Push Backend Image
      # -----------------------------
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./code/petmanagement_backend_rajalakshmi
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/findpet-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/findpet-backend:${{ github.sha }}

      # -----------------------------
      # Step 7: Build & Push Frontend Image
      # -----------------------------
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./code/petmanagement_frontend_rajalakshmi
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/findpet-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/findpet-frontend:${{ github.sha }}

      # -----------------------------
      # Step 8: Deploy to EC2 & update docker-compose
      # -----------------------------
      # -----------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          debug: true
          envs: DOCKER_USERNAME
          script: |
            set -e
            echo "🚀 Starting deployment..."
            cd /home/ubuntu/Find_Pet/code
            echo "Docker username: ${DOCKER_USERNAME}"
            cp docker-compose.yml docker-compose.yml.bak
            sed -i "s|  build:.*petmanagement_backend_rajalakshmi|  image: ${DOCKER_USERNAME}/findpet-backend:latest|" docker-compose.yml
            sed -i "s|  build:.*petmanagement_frontend_rajalakshmi|  image: ${DOCKER_USERNAME}/findpet-frontend:latest|" docker-compose.yml
            docker compose pull
            docker compose up -d
            echo "✅ Deployment complete."

